"""Ensambla DEFAULT_CONFIG desde los fragmentos por bloque de config/blocks/.

El orden de las claves se preserva (importa para el oocode.json generado por primera vez).
"""
from config.blocks import (
    api,
    agents,
    permissions,
    context,
    embeddings,
    tools,
    workspace,
    searxng,
    logging,
    appearance,
    plugins,
    plugin_options,
    skills,
    models,
    fallback,
    mcp,
    hooks,
    snapshots,
    rag,
    vision,
    completion,
    chatlog,
    webui,
    subagents,
    backup,
)

DEFAULT_CONFIG: dict = {
    "api": api.DEFAULTS,
    "agents": agents.DEFAULTS,
    "permissions": permissions.DEFAULTS,
    "context": context.DEFAULTS,
    "embeddings": embeddings.DEFAULTS,
    "tools": tools.DEFAULTS,
    "workspace": workspace.DEFAULTS,
    "searxng": searxng.DEFAULTS,
    "logging": logging.DEFAULTS,
    "appearance": appearance.DEFAULTS,
    "plugins": plugins.DEFAULTS,
    "pluginOptions": plugin_options.DEFAULTS,
    "skills": skills.DEFAULTS,
    "models": models.DEFAULTS,
    "fallback": fallback.DEFAULTS,
    "mcp": mcp.DEFAULTS,
    "hooks": hooks.DEFAULTS,
    "snapshots": snapshots.DEFAULTS,
    "rag": rag.DEFAULTS,
    "vision": vision.DEFAULTS,
    "completion": completion.DEFAULTS,
    "chatlog": chatlog.DEFAULTS,
    "webui": webui.DEFAULTS,
    "subagents": subagents.DEFAULTS,
    "backup": backup.DEFAULTS,
}
