# Generado desde el antiguo config.py — bloque 'permissions' de DEFAULT_CONFIG.
DEFAULTS = {
    # Core tools
    "bash":              "ask",
    "write_file":        "ask",
    "edit_file":         "ask",
    "read_file":         "auto",
    "list_dir":          "auto",
    "web_search":        "auto",
    "web_fetch":         "auto",
    "searxng_search":    "auto",
    "spawn_subagent":    "ask",
    "explore":           "auto",
    "create_team":       "ask",
    "run_team":          "ask",
    # Linting (MCP tools)
    "lint_file":         "auto",
    "lint_project":      "auto",
    # Git (MCP tools — read-only → auto, write → ask)
    "git_status":        "auto",
    "git_diff":          "auto",
    "git_log":           "auto",
    "git_commit":        "ask",
    "git_push":          "ask",
    "git_pull":          "ask",
    "git_add":           "ask",
    "git_branch":        "auto",
    "git_stash":         "ask",
    "git_patch":         "ask",
    "git_clone":         "ask",
    "git_worktree":      "ask",
    # Tests (plugin test_runner) — solo verifican, no modifican ficheros
    "run_tests":         "auto",
    "test_file":         "auto",
    # Docker (MCP tools — read-only → auto, write → ask)
    "docker_ps":         "auto",
    "docker_logs":       "auto",
    "docker_inspect":    "auto",
    "docker_images":     "auto",
    "docker_exec":       "ask",
    "docker_stop":       "ask",
    "docker_rm":         "ask",
    "docker_cp":         "ask",
    # Docker Compose (MCP tools — read-only → auto, write → ask)
    "compose_version":   "auto",
    "compose_services":  "auto",
    "compose_status":    "auto",
    "compose_config":    "auto",
    "compose_images":    "auto",
    "compose_top":       "auto",
    "compose_logs":      "auto",
    "compose_up":        "ask",
    "compose_down":      "ask",
    "compose_stop":      "ask",
    "compose_restart":   "ask",
    "compose_build":     "ask",
    "compose_pull":      "ask",
    "compose_exec":      "ask",
    "compose_run":       "ask",
    # Embeddings (plugin embeddings_search)
    "index_workspace":   "auto",
    "semantic_search":   "auto",
    # code_search (read-only)
    "code_search":       "auto",
    # edit_files (atómico — requiere confirmación)
    "edit_files":        "ask",
    # Búsqueda de código (MCP bundled — read-only)
    "grep_code":         "auto",
    "multi_grep":        "auto",
    "code_outline":      "auto",
    "read_sections":     "auto",
    "affected_files":    "auto",
    "symbol_lookup":     "auto",
    "code_compare":      "auto",
    "find_files":        "auto",
    "read_files":        "auto",
    "diff_files":        "auto",
    "http_get":          "auto",
    "calculate":         "auto",
    "env_check":         "auto",
    "json_format":       "auto",
    "hash_text":         "auto",
    "port_check":        "auto",
    "search_todos":      "auto",
    "run_quick_check":   "auto",
    "system_info":       "auto",
    "list_recent_files": "auto",
    "read_project_file": "auto",
    "get_datetime":      "auto",
    "process_list":      "auto",
    # LSP plugin (read-only → auto; escribe fichero → ask)
    "lsp_definition":      "auto",
    "lsp_references":      "auto",
    "lsp_hover":           "auto",
    "lsp_symbols":         "auto",
    "lsp_diagnostics":     "auto",
    "lsp_completion":      "auto",
    "lsp_type_definition":    "auto",
    "lsp_implementation":     "auto",
    "lsp_code_actions":       "auto",
    "lsp_workspace_symbols":  "auto",
    "lsp_call_hierarchy":     "auto",
    "lsp_rename":             "ask",   # puede modificar múltiples ficheros
    "lsp_format":             "ask",   # modifica el fichero
    "lsp_restart":            "auto",  # solo reinicia el servidor, no modifica ficheros
    # ctags plugin
    "build_symbol_index": "ask",
    "find_symbol":        "auto",
    "list_symbols":       "auto",
    # Filesystem tools (MCP) — lectura → auto, escritura/destructivo → ask
    "ls_file":            "auto",
    "ls_dir":             "auto",
    "find_file":          "auto",
    "find_dir":           "auto",
    "grep_file":          "auto",
    "chmod_file":         "ask",
    "chmod_dir":          "ask",
    "chown_file":         "ask",
    "chown_dir":          "ask",
    "mv_file":            "ask",
    "cp_file":            "ask",
    "rm_file":            "ask",
    "rm_dir":             "ask",
    "mkdir_dir":          "ask",
    "touch_file":         "ask",
    # Debug de procesos (ask por impacto)
    "strace_run":         "ask",
    "gdb_run":            "ask",
    "pdb_run":            "ask",
    "valgrind_run":       "ask",
    # Build y ejecución
    "make_run":           "ask",
    "run_script":         "ask",
    "format_code":        "ask",
    "mypy_check":         "auto",
    # Python tools
    "python_exec":        "auto",
    "pip_tool":           "ask",
    # Node.js tools
    "npm_tool":           "ask",
    # Archive
    "archive_extract":    "ask",
    "archive_create":     "ask",
    "archive_list":       "auto",
    # Metadatos de ficheros
    "file_stat":          "auto",
    "symlink_create":     "ask",
    "readlink":           "auto",
    # Parches y edición avanzada
    "patch_apply":        "ask",
    "regex_replace":      "ask",
    "bulk_replace":       "ask",
    # Edición segura compuesta
    "smart_replace":      "ask",
    "context_before_edit":"auto",
    "pre_edit_check":     "auto",
    # Visualización y análisis
    "tree":               "auto",
    "analyze_codebase":   "auto",   # meta-tool: tree+count+grep en una llamada (lectura)
    # Markdown y XML
    "render_markdown":    "auto",   # lectura/validación Markdown
    "xml_format":         "auto",   # formato XML (puede escribir si se pasa output)
    "xml_validate":       "auto",   # validación XML (solo lectura)
    # Linters especializados
    "gitlint_check":      "auto",   # solo lectura git + gitlint
    "ansible_lint":       "auto",   # solo lectura + ansible-lint
    "efm_config_update":  "auto",   # escribe ~/.oocode/efm-langserver.yaml
    "count_lines":        "auto",   # lectura — cuenta líneas de un fichero
    "template_fill":      "auto",   # renderizado de plantillas (no escribe)
    # System Assistant MCP — lectura → auto, escritura/acción → ask
    "systemctl_status":   "auto",
    "systemctl_action":   "ask",
    "journalctl":         "auto",
    "net_interfaces":     "auto",
    "net_connections":    "auto",
    "net_ping":           "auto",
    "net_dns":            "auto",
    "disk_usage":         "auto",
    "disk_inodes":        "auto",
    "dir_size":           "auto",
    "lsblk_info":         "auto",
    "user_list":          "auto",
    "user_info":          "auto",
    "group_list":         "auto",
    "who_logged":         "auto",
    "ps_list":            "auto",
    "top_snapshot":       "auto",
    "kill_process":       "ask",
    "fw_status":          "auto",
    "fw_rules":           "auto",
    "fw_allow":           "ask",
    "fw_deny":            "ask",
    "sys_info":           "auto",
    "sys_updates":        "auto",
    "sys_logs":           "auto",
    "env_vars":           "auto",
    "cron_list":          "auto",
    "apt_update":         "ask",
    "apt_upgrade":        "ask",
    "apt_install":        "ask",
    "apt_remove":         "ask",
    "apt_search":         "auto",
    "apt_info":           "auto",
    "apt_list_installed": "auto",
    "dnf_update":         "auto",
    "dnf_install":        "ask",
    "dnf_remove":         "ask",
    "dnf_search":         "auto",
    "dnf_info":           "auto",
    "rpm_query":          "auto",
    # Tree-sitter plugin (read-only)
    "extract_functions": "auto",
    "extract_classes":   "auto",
    "extract_imports":   "auto",
    "ast_summary":       "auto",
    # Todo plugin
    "todo_list":         "auto",
    "todo_add":          "ask",
    "todo_done":         "auto",
    "todo_sync":         "auto",
    # Changelog plugin (read-only)
    "changelog_today":   "auto",
    "changelog_session": "auto",
    "changelog_week":    "auto",
    # Clipboard plugin
    "clipboard_copy":    "auto",
    "clipboard_paste":   "auto",
    # Vault plugin
    "vault_list":        "auto",
    "vault_get":         "auto",
    # Workspace — guardar instrucciones persistentes
    "workspace_remember": "auto",
    # Memoria persistente del agente
    "mem_save":           "auto",
    # Planificación autónoma del agente
    "plan_create":        "auto",
    "task_done":          "auto",
    "ask_user":           "auto",   # preguntar al usuario no requiere permiso (sería circular)
    # Git nuevas tools
    "git_blame":          "auto",
    "git_rebase":         "ask",
    "git_tag":            "ask",
    "git_cherry_pick":    "ask",
    # Validación y procesado
    "json_validate":      "auto",
    "yaml_validate":      "auto",
    "jq_query":           "auto",
    # Skills (converters + snippets — pure computation)
    "encode_base64":     "auto",
    "decode_base64":     "auto",
    "url_encode":        "auto",
    "url_decode":        "auto",
    "compute_hash":      "auto",
    "to_base":           "auto",
    "format_json":       "auto",
    "escape_string":     "auto",
    "hex_encode":        "auto",
    "hex_decode":        "auto",
    "snippet_save":      "auto",
    "snippet_get":       "auto",
    "snippet_list":      "auto",
    "snippet_delete":    "auto",
    # IoT assistant
    "tapo_list":       "auto",
    "tapo_status":     "auto",
    "tapo_on_off":     "ask",
    "tapo_set":        "ask",
    "blink_status":    "auto",
    "blink_arm":       "ask",
    "blink_snapshot":  "ask",
    "blink_clips":     "auto",
    "blink_verify":    "auto",
    "alexa_devices":   "auto",
    "alexa_speak":     "ask",
    "alexa_command":   "ask",
    "alexa_volume":    "ask",
    "tuya_list":       "auto",
    "tuya_status":     "auto",
    "tuya_control":    "ask",
    "ha_entities":     "auto",
    "ha_state":        "auto",
    "ha_control":      "ask",
    "ha_automation":   "ask",
    "mqtt_publish":    "ask",
    "mqtt_subscribe":  "auto",
    "esphome_list":    "auto",
    "esphome_control": "ask",
    "iot_discover":    "auto",
    # Security assistant (read-only/analysis = auto; offensive = ask)
    "nmap_scan":           "ask",
    "port_scan":           "auto",
    "ssl_check":           "auto",
    "whois_lookup":        "auto",
    "dns_enum":            "auto",
    "http_headers":        "auto",
    "nikto_scan":          "ask",
    "gobuster_run":        "ask",
    "curl_request":        "auto",
    "encode_decode":       "auto",
    "hash_crack":          "ask",
    "jwt_decode":          "auto",
    "cert_inspect":        "auto",
    "log_analyze":         "auto",
    "secret_scan":         "auto",
    "cve_lookup":          "auto",
    "xor_decode":          "auto",
    "steganography_check": "auto",
    "base_convert":        "auto",
    "hex_dump":            "auto",
    "fw_audit":            "auto",
    "ssh_key_audit":       "auto",
    "sudoers_review":      "auto",
    "file_integrity_check": "auto",
    # HTTP Client assistant
    "http_request":       "auto",
    "http_auth":          "auto",
    "http_upload":        "ask",
    "response_diff":      "auto",
    "openapi_validate":   "auto",
    "curl_import":        "ask",
    "websocket_send":     "auto",
    "sse_listen":         "auto",
    "mock_server_start":  "ask",
    "mock_server_stop":   "ask",
    "http_health_check":  "auto",
    "graphql_query":      "auto",
    "http_batch":         "ask",
    "http_history":       "auto",
    # Database assistant MCP — lectura/análisis → auto; escritura/SQL arbitrario → ask
    "csv_to_sqlite":        "ask",
    "db_connect":           "auto",
    "db_explain":           "auto",
    "db_export":            "auto",
    "db_import":            "ask",
    "db_indices":           "auto",
    "db_migrate_check":     "auto",
    "db_query":             "ask",
    "db_schema":            "auto",
    "db_stats":             "auto",
    "db_tables":            "auto",
    "mysql_explain":        "auto",
    "mysql_query":          "ask",
    "mysql_schema":         "auto",
    "pg_explain":           "auto",
    "pg_query":             "ask",
    "pg_schema":            "auto",
    "sql_format":           "auto",
    "sqlite_backup":        "ask",
    "sqlite_bulk_insert":   "ask",
    "sqlite_create_table":  "ask",
    "sqlite_delete":        "ask",
    "sqlite_explain":       "auto",
    "sqlite_export":        "auto",
    "sqlite_fts_search":    "auto",
    "sqlite_indices":       "auto",
    "sqlite_insert":        "ask",
    "sqlite_query":         "ask",
    "sqlite_schema":        "auto",
    "sqlite_tables":        "auto",
    "sqlite_to_csv":        "auto",
    "sqlite_update":        "ask",
    "sqlite_vacuum":        "ask",
    # Home Office assistant MCP — lectura → auto; creación/escritura/envío → ask
    "apply_cell_formatting":          "ask",
    "apply_document_theme":           "ask",
    "asset_register_add":             "ask",
    "cal_add":                        "ask",
    "cal_list":                       "auto",
    "cal_search":                     "auto",
    "cmdb_search":                    "auto",
    "cmdb_update":                    "ask",
    "contact_search":                 "auto",
    "csv_analyze":                    "auto",
    "doc_add_content_block":          "ask",
    "doc_add_header_footer":          "ask",
    "doc_add_toc":                    "ask",
    "doc_apply_style":                "ask",
    "doc_compare":                    "auto",
    "doc_convert":                    "ask",
    "doc_create":                     "ask",
    "doc_create_from_template":       "ask",
    "doc_create_rfc":                 "ask",
    "doc_embed_image":                "ask",
    "doc_extract_metadata":           "auto",
    "doc_fill_corporate_template":    "ask",
    "doc_fill_template":              "ask",
    "doc_list_templates":             "auto",
    "doc_project_save":               "ask",
    "doc_read":                       "auto",
    "doc_read_template_fields":       "auto",
    "doc_set_page_layout":            "ask",
    "doc_set_table_style":            "ask",
    "doc_update_section":             "ask",
    "doc_version_bump":               "ask",
    "doc_word_count":                 "auto",
    "email_list":                     "auto",
    "email_read":                     "auto",
    "email_search":                   "auto",
    "email_send":                     "ask",
    "image_to_text":                  "auto",
    "insert_chart":                   "ask",
    "notes_list":                     "auto",
    "notes_save":                     "ask",
    "notes_search":                   "auto",
    "pdf_extract_text":               "auto",
    "pptx_add_notes":                 "ask",
    "pptx_add_slide":                 "ask",
    "pptx_create":                    "ask",
    "pptx_create_from_template":      "ask",
    "pptx_insert_chart":              "ask",
    "pptx_read":                      "auto",
    "pptx_set_background":            "ask",
    "project_context_read":           "auto",
    "project_init_office":            "ask",
    "set_paragraph_format":           "ask",
    "xlsx_add_data_validation":       "ask",
    "xlsx_add_sheet":                 "ask",
    "xlsx_append_row":                "ask",
    "xlsx_apply_conditional_format":  "ask",
    "xlsx_create_report":             "ask",
    "xlsx_create_table":              "ask",
    "xlsx_fill_range":                "ask",
    "xlsx_freeze_panes":              "ask",
    "xlsx_insert_chart":              "ask",
    "xlsx_merge_cells":               "ask",
    "xlsx_protect_sheet":             "ask",
    "xlsx_read":                      "auto",
    "xlsx_set_column_width":          "ask",
    "xlsx_write":                     "ask",
}
